In [95]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans

In [115]:
url_dataset = "./data/bezdekIris.data"
data = pd.read_csv(url_dataset)
print(data)
# Xáo trộn dữ liệu + xoá chỉ mục hàng 
data = data.sample(frac=1).reset_index(drop=True)
data = data.to_numpy() #numpy type
y = data[:,-1]
data = np.delete(data, -1, axis = 1)
data

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


array([[5.1, 3.4, 1.5, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.7, 3.3, 5.7, 2.1],
       [5.0, 3.3, 1.4, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [6.3, 3.3, 6.0, 2.5],
       [5.0, 3.4, 1.5, 0.2],
       [6.8, 3.0, 5.5, 2.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.7, 2.5, 5.8, 1.8],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [6.1, 2.9, 4.7, 1.4],
       [4.7, 3.2, 1.3, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [6.7, 3.1, 4.7, 1.5],
       [7.7, 3.0, 6.1, 2.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.8, 5.1, 1.5],
       [6.6, 3.0, 4.4, 1.4],
       [5.4, 3.0, 4.5, 1.5],
       [5.5, 2.3, 4.0, 1.3],
       [7.0, 3.2, 4.7, 1.4],
       [7.7, 2.8, 6.7, 2.0],
       [6.4, 2.9, 4.3, 1.3],
       [6.4, 3.2, 5.3, 2.3],
       [6.0, 2.9, 4.5, 1.5],
       [5.8, 2.6, 4.0, 1.2],
       [6.9, 3.1, 5.4, 2.1],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.4, 3

In [116]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(data)
print('Centers found by scikit-learn:')
print(kmeans.cluster_centers_)


Centers found by scikit-learn:
[[6.85       3.07368421 5.74210526 2.07105263]
 [5.00408163 3.42653061 1.46326531 0.24693878]
 [5.9016129  2.7483871  4.39354839 1.43387097]]


In [117]:
print("origin")
names = {'Iris-setosa':0,'Iris-versicolor':1, 'Iris-virginica':2}

print(y.shape)
for i in range(len(y)):
    y[i] = names[y[i]]
print(y)
print(kmeans.labels_)

origin
(149,)
[0 1 2 0 0 2 0 2 0 2 0 0 0 2 1 0 0 1 2 0 1 2 1 1 1 1 2 1 2 1 1 2 0 0 0 1 1
 1 0 0 0 0 2 1 2 1 2 2 1 1 2 1 0 1 1 2 1 0 1 2 0 0 1 1 2 1 1 2 2 1 2 1 2 2
 1 0 1 2 2 1 0 0 0 2 0 0 1 2 2 0 1 0 2 2 0 1 2 2 1 2 0 1 0 1 1 2 0 1 0 2 0
 2 1 0 2 0 1 2 0 2 0 1 2 1 2 2 1 1 0 1 0 1 2 2 0 2 0 2 2 2 1 0 0 0 0 1 0 2
 2]
[1 2 0 1 1 0 1 0 1 0 1 1 1 2 2 1 1 2 0 1 2 2 2 2 2 2 0 2 0 2 2 0 1 1 1 2 2
 2 1 1 1 1 2 2 0 2 2 0 2 2 2 0 1 2 2 0 2 1 2 0 1 1 2 2 2 2 2 0 2 2 0 2 0 2
 2 1 2 2 0 2 1 1 1 0 1 1 2 0 0 1 2 1 2 0 1 0 0 0 2 0 1 2 1 2 2 0 1 2 1 2 1
 0 2 1 0 1 2 0 1 0 1 2 2 2 2 0 2 2 1 2 1 2 0 0 1 0 1 2 0 0 2 1 1 1 1 2 1 0
 0]
